export const ALL_MOVIE_REQUEST='ALL_MOVIE_REQUEST';
export const ALL_MOVIE_SUCCESS='ALL_MOVIE_SUCCESS';
export const ALL_MOVIE_FAIL='ALL_MOVIE_FAIL';
export const CLEAR_ERRORS='CLEAR_ERRORS';

export const LOAD_WATCHLIST_REQUEST='LOAD_WATCHLIST_REQUEST';
export const LOAD_WATCHLIST_SUCCESS='LOAD_WATCHLIST_SUCCESS';
export const LOAD_WATCHLIST_FAIL='LOAD_WATCHLIST_FAIL';

